[package]
name = "Multi-token_Pool"
version = "1.0.0"
authors = []

[addresses]
pool_addr = 'a4f9986ef81ebc6fa038bb6ac4c7f7002b9d856d37bf79961a5955ff5dff3cd6'
pool_deployed_addr = '1446c2e0eb894d1697ee161c38e5f824aa28569dfaa1c9ed47b58e12a4db7e00'
lst_addr = '1446c2e0eb894d1697ee161c38e5f824aa28569dfaa1c9ed47b58e12a4db7e00'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
