[package]
name = "Multi-token_Pool"
version = "1.0.0"
authors = []

[addresses]
pool_addr = 'a4f9986ef81ebc6fa038bb6ac4c7f7002b9d856d37bf79961a5955ff5dff3cd6'
pool_deployed_addr = '0xbe65a7ad7d1f4ee10d5700c9b7e56f091b2a669b044a1477b47821964fdc3f6f'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
